// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

#pragma once

#include "../network/json/serialization_json.hpp"
#include <string>
#include <utility>
#include <vector>

namespace dropbox {

struct ItemList final {
    std::vector<std::string> items;

    JSON_SERIALIZE("items", items)
    ItemList(std::vector<std::string> items_)
    : items(std::move(items_))
    {}
    ItemList() {};
};

}  // namespace dropbox
