// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from example.djinni

package com.dropbox.textsort;

import java.util.ArrayList;

public final class ItemList {


    /*package*/ final ArrayList<String> items;

    public ItemList(
            ArrayList<String> items) {
        this.items = items;
    }

    public ArrayList<String> getItems() {
        return items;
    }

    @Override
    public String toString() {
        return "ItemList{" +
                "items=" + items +
        "}";
    }

}
